- docs/charts/scatter-plot.md
- src/ScatterPlot/ScatterPlot.story.tsx
- src/docs.story.tsx
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```
Issue Number: N/A
Added scatter plot documentation in storybook
```
[ ] Yes
[x] No
```
N/A
> Scatter plot docs

- docs/README.md
- docs/charts/bubble-chart.md
- package-lock.json
- src/docs.story.tsx
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```
Issue Number: N/A
Added bubble chart documentation in storybook
```
[ ] Yes
[x] No
```
N/A
> Bubble chart docs

- src/common/Axis/RadialAxis/RadialAxis.story.tsx
- src/common/Axis/RadialAxis/RadialAxis.tsx
- src/common/Axis/RadialAxis/RadialAxisArcSeries/RadialAxisArc.tsx
- src/common/Axis/RadialAxis/RadialAxisArcSeries/RadialAxisArcSeries.tsx
- src/common/Axis/RadialAxis/RadialAxisArcSeries/index.tsx
- src/common/Axis/RadialAxis/RadialAxisLineSeries/RadialAxisLine.tsx
- src/common/Axis/RadialAxis/RadialAxisLineSeries/RadialAxisLineSeries.tsx
- src/common/Axis/RadialAxis/RadialAxisLineSeries/index.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTick.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickLabel.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickLine.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickSeries.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/index.tsx
- src/common/Axis/RadialAxis/index.tsx
- src/common/utils/formatting.tsx
This PR:
- Refactors the Radial Axes API to be declarative JSX elements
- Adds support to make the date formatting better
> Refactor Radial Axes API

- src/RadialBarChart/RadialBarChart.story.tsx
- src/RadialBarChart/RadialBarChart.tsx
- src/RadialBarChart/RadialBarSeries/PosedRadialBar.tsx
- src/RadialBarChart/RadialBarSeries/RadialBar.tsx
- src/RadialBarChart/RadialBarSeries/RadialBarSeries.tsx
- src/RadialBarChart/RadialBarSeries/index.ts
- src/RadialBarChart/index.ts
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickSeries.tsx
- src/common/utils/formatting.tsx
- src/common/utils/ticks.tsx
This PR:
- Adds a new Radial Bar Chart
- Fixes Radial Axes not accepting categorical datasets
> Radial Bar Chart

- src/RadialAreaChart/RadialAreaChart.story.tsx
- src/RadialAreaChart/RadialAreaChart.tsx
- src/RadialAreaChart/RadialAreaSeries/RadialArea.tsx
- src/RadialAreaChart/RadialAreaSeries/RadialAreaSeries.tsx
- src/RadialAreaChart/RadialAreaSeries/RadialLine.tsx
- src/RadialAreaChart/index.ts
- src/RadialBarChart/RadialBarChart.story.tsx
- src/RadialBarChart/RadialBarChart.tsx
- src/RadialScatterPlot/RadialScatterPlot.story.tsx
- src/RadialScatterPlot/RadialScatterPlot.tsx
- src/common/Axis/RadialAxis/RadialAxis.story.tsx
- src/common/Axis/RadialAxis/RadialAxis.tsx
- src/common/Axis/RadialAxis/RadialAxisArcSeries/RadialAxisArc.tsx
- src/common/Axis/RadialAxis/RadialAxisArcSeries/RadialAxisArcSeries.tsx
- src/common/Axis/RadialAxis/RadialAxisLineSeries/RadialAxisLineSeries.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTick.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickLabel.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickSeries.tsx
- src/common/CircleSeries/PosedCircle.tsx
- src/common/Styles/RadialGradient.tsx
- src/common/utils/animations.tsx
- src/common/utils/interpolation.tsx
This PR:
- Adds radial axis to radial bar
- Adds radial axis to radial area
- Adds radial axis to radial scatter
- Fixes pose transition w/ scatter plot transforms
- Add ability to set interpolation for radial areas
- Add automation label rotation for radial axis labels
- Tweak radial gradient styles
- Fix radial gradient r position
- Refactors to radial axis apis
> Radial Axis Integrations

- src/HivePlot/HiveAxis/HiveAxis.tsx
- src/HivePlot/HiveLabel/HiveLabel.tsx
- src/HivePlot/HiveLink/HiveLink.tsx
- src/HivePlot/HiveNode/HiveNode.tsx
- src/HivePlot/HivePlot.tsx
- src/HivePlot/HiveTooltip/HiveTooltip.tsx
- src/HivePlot/index.tsx
- src/HivePlot/types.tsx
- src/RadialAreaChart/RadialAreaSeries/RadialArea.tsx
- src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.tsx
- src/Sankey/SankeyLabel/SankeyLabel.tsx
- src/common/utils/index.ts
- src/common/utils/math.ts
This PR contains various code cleanup fixes.
> Code Cleanup

- src/RadialAreaChart/RadialAreaChart.tsx
- src/RadialAreaChart/RadialAreaSeries/RadialArea.tsx
- src/RadialAreaChart/RadialAreaSeries/RadialAreaSeries.tsx
- src/RadialAreaChart/RadialAreaSeries/RadialLine.tsx
- src/RadialScatterPlot/RadialScatterSeries/RadialScatterPoint.tsx
- src/RadialScatterPlot/RadialScatterSeries/RadialScatterSeries.tsx
- src/common/Axis/RadialAxis/RadialAxisArcSeries/RadialAxisArc.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickLine.tsx
- src/common/CircleSeries/RadialCircleSeries.tsx
- src/common/CircleSeries/index.ts
- src/common/TooltipArea/TooltipArea.tsx
- src/common/utils/children.tsx
This PR:
- Adds Radial Area Chart Tooltip and Circles
- Enhanced TooltipArea to handle radial charts
- Removes pointer events from radial axis
- Adds ability to pass color conditionally to radial scatter
- Adds ability to pass visibility function to radial scatter
- Fixes bug with child clone invoking undefined functions
> Radial area

- package-lock.json
- package.json
- src/RadialAreaChart/RadialAreaSeries/RadialAreaSeries.tsx
- src/common/TooltipArea/TooltipArea.tsx
- tsconfig.json
This PR fixes typescript errors and tightens ts checking.
> TypeScript Tightening

- src/common/TooltipArea/TooltipArea.tsx
This PR fixes null ref exception on tooltip area.
> Fix Tooltip TS Exception

- docs/getting-started/css-vars.md
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```
Without the import, there are various styles that don't look right. For example, the background for the popper on hover doesn't work, some configurations are also affected such as `<Bar rounded={true} />` since it relies on setting a class on the element.
Issue Number: N/A
No new behavior. Just updated docs to include the import line.
```
[ ] Yes
[x] No
```
> Update docs to include CSS import

- src/BarChart/BarChart.story.tsx
- src/BarChart/BarChart.tsx
- src/BarChart/BarSeries/Bar.tsx
- src/BarChart/BarSeries/BarSeries.tsx
- src/common/Axis/LinearAxis/LinearAxisLine.tsx
- src/common/Axis/LinearAxis/LinearAxisTickLabel.tsx
- src/common/Axis/LinearAxis/LinearAxisTickLine.tsx
- src/common/Axis/LinearAxis/LinearXAxis.tsx
- src/common/Axis/LinearAxis/LinearYAxis.tsx
- src/common/data/index.tsx
- src/common/data/waterfall.ts
This PR:
- Adds ability to do waterfall bar charts 
- Adds ability to pass classNames to axis components
- Fix modifiers getting overridden in bar charts
> Waterfall Bar Chart Type

- src/common/legends/DiscreteLegend/DiscreteLegend.story.tsx
- src/common/legends/DiscreteLegend/DiscreteLegendEntry.module.scss
- src/common/legends/DiscreteLegend/DiscreteLegendEntry.tsx
This PR adds ability to make label orientation horz or vertical.
> Legend Entry Label Orientation

- src/BarChart/BarChart.story.tsx
- src/BarChart/BarChart.tsx
- src/common/Axis/LinearAxis/LinearAxis.tsx
- src/common/Axis/LinearAxis/LinearAxisTickSeries.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickSeries.tsx
- src/common/Gridline/GridlineSeries.tsx
- src/common/ZoomPan/ChartZoomPan.tsx
- src/common/demo/category.tsx
- src/common/scales/basic.tsx
- src/common/utils/ticks.test.ts
- src/common/utils/ticks.tsx
This scales the ticks to be more round duration values. The formatting of the ticks is still left up to the caller though. In these screenshots below, I used humanFormat for the tick formatting:
> Add a new duration axis type which calculates better ticks

- src/common/Brush/BrushHandle.tsx
- src/common/Brush/BrushSlice.tsx
- src/common/Gestures/Pan.tsx
- src/common/Gestures/Zoom.tsx
- src/common/ZoomPan/ChartZoomPan.tsx
- src/common/ZoomPan/ZoomPan.tsx
This PR:
- Adds ability to pan/zoom X and Y
- Adds API type to determine action (zoom vs pan)
- Adds ability to pan an uncontained canvas
- Adds ability to have a min zoom
> Zoom + Pan Improvements

- src/common/scales/radial.ts
This PR fixes 0 based radial scales causing it to be sqrt which results in a non-zero result.
> Fix 0 Based Radial Scales

- src/common/Brush/Brush.tsx
- src/common/Brush/BrushHandle.tsx
- src/common/Brush/BrushSlice.tsx
- src/common/Gestures/Move.tsx
- src/common/Gestures/index.ts
This PR refactors the mouse and touch events into a single component and updates brush to use them.
Couple of notes: 
- Need to go through and fix types
- Need to improve the brush clientX/Y checking to not be so hacky
> Refactor Touch/Mouse

- CHANGELOG.md
- package.json
- src/common/Gestures/Pan.tsx
- src/common/ZoomPan/ZoomPan.story.tsx
This PR fixes decay not working on Y axis
> Fix Decay on Y Axis

- src/AreaChart/AreaSeries/PointSeries.tsx
This PR fixes the area point tooltip showing on hover of points.
> Fix Area Point Tooltip Showing

- src/PieChart/PieArcSeries/PieArcLabel/PieArcLabel.tsx
- src/PieChart/PieArcSeries/PieArcSeries.tsx
- src/PieChart/PieChart.story.tsx
- src/common/demo/numbers.tsx
Fix label position overlap with pie charts.
> Fix Pie Label Overlap

- src/AreaChart/AreaChart.story.tsx
- src/AreaChart/AreaChart.tsx
- src/AreaChart/AreaSeries/Line.tsx
- src/BarChart/BarChart.tsx
- src/LineChart/LineChart.story.tsx
- src/RadialAreaChart/RadialAreaSeries/RadialPointSeries.tsx
- src/common/Axis/LinearAxis/LinearAxisTickLine.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickLabel.tsx
- src/common/Axis/RadialAxis/RadialAxisTickSeries/RadialAxisTickLine.tsx
- src/common/Brush/Brush.tsx
- src/common/Brush/BrushHandle.tsx
- src/common/Brush/BrushSlice.tsx
- src/common/Gridline/GridStripe.tsx
- src/common/Gridline/Gridline.tsx
- src/common/MarkLine/MarkLine.tsx
- src/common/TooltipArea/ChartTooltip.tsx
- src/common/TooltipArea/Tooltip.tsx
- src/common/TooltipArea/TooltipArea.tsx
- src/common/TooltipArea/TooltipTemplate.tsx
- src/common/containers/ChartContainer.tsx
- src/common/demo/dates.tsx
- src/common/demo/utils.tsx
- src/common/gradients/GradientStop.tsx
- src/common/legends/DiscreteLegend/DiscreteLegendSymbol.tsx
- src/common/masks/Mask.tsx
- src/common/masks/Stripes.tsx
This PR:
- Updates code style to favor destructuring
- Adds PureComponents where possible
- Adds max line/area tooltip counts
- Includes rdk css by default
> Tooltip Fixes

- src/AreaChart/AreaSeries/Area.tsx
- src/AreaChart/AreaSeries/Line.tsx
- src/BarChart/BarChart.story.tsx
- src/BarChart/BarSeries/Bar.tsx
- src/LineChart/LineChart.story.tsx
- src/ScatterPlot/ScatterSeries/ScatterPoint.tsx
- src/common/Brush/Brush.story.tsx
- src/common/utils/functions.ts
- src/common/utils/index.ts
Add ability to do callbacks for style/classname in line,area,bar,scatter.
> Prop Callbacks

- src/RadialBarChart/RadialBarSeries/RadialBarSeries.tsx
- src/RadialGauge/RadialGaugeSeries/RadialGaugeSeries.tsx
- src/Sankey/Sankey.tsx
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```
Issue Number: N/A
Sankey chart colors were broken after previous commit. Also fixed radial gauge and radial bar chart colors as well.
```
[ ] Yes
[x] No
```
> fix sankey and radial charts color regression

- .storybook/config.js
- .storybook/webpack.config.js
- demo/category.tsx
- demo/dates.tsx
- src/BarChart/BarChart.story.tsx
- src/BarChart/BarChart.tsx
- src/BarChart/BarSeries/Bar.tsx
- src/BarChart/BarSeries/BarSeries.tsx
- src/common/Gridline/GridlineSeries.tsx
- src/common/data/barStack.tsx
- src/common/data/marimekko.tsx
- src/common/scales/basic.tsx
- src/common/utils/domains.tsx
This PR:
- Adds new diverging stacked bar chart
- Adds RDK CSS to storybook config
- Fixes types on category data type
- Adds webpack typescript compilation to demo code
- Fixes normalized horz bar chart demo
- Fixes horz stacked bar color getter
- Fixes stacked bar charts custom widths
> Diverging Stacked Bar Charts

- CHANGELOG.md
- src/Heatmap/Heatmap.story.tsx
- src/common/legends/SequentialLegend/SequentialLegend.module.scss
- src/common/legends/SequentialLegend/SequentialLegend.story.tsx
- src/common/legends/SequentialLegend/SequentialLegend.tsx
- src/common/legends/SequentialLegend/index.ts
This PR adds a new sequential legend.
> Sequential Legends

- package-lock.json
- src/AreaChart/AreaChart.story.tsx
- src/BarChart/BarChart.story.tsx
- src/Heatmap/CalendarHeatmap.tsx
- src/Heatmap/calendarUtils.ts
- src/PieChart/PieChart.story.tsx
- src/RadialBarChart/RadialBarChart.tsx
- src/common/data/barStack.ts
- src/common/legends/SequentialLegend/SequentialLegend.tsx
- src/common/scales/basic.ts
- src/common/utils/array.ts
Here is the details of the lint errors:
```
ERROR in /jasklabs/admiral/ui/src/shared/reaviz/src/AreaChart/AreaChart.story.tsx(104,41):
TS2322: Type '{ key: Date; data: number[]; }[]' is not assignable to type 'ChartDataShape[]'.
Type '{ key: Date; data: number[]; }' is not assignable to type 'ChartDataShape'.
Type '{ key: Date; data: number[]; }' is not assignable to type 'BaseChartDataShape<BaseChartDataShape<ChartDataTypes>[]>'.
Types of property 'data' are incompatible.
Type 'number[]' is not assignable to type 'BaseChartDataShape<ChartDataTypes>[]'.
Type 'number' is not assignable to type 'BaseChartDataShape<ChartDataTypes>'.
ERROR in /jasklabs/admiral/ui/src/shared/reaviz/src/BarChart/BarChart.story.tsx(37,3):
TS6133: 'LinearXAxisTickLine' is declared but its value is never read. …
```
> Fixed all lint errors found internally
